CREATE TABLE folders_table(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder TEXT NOT NULL,
    content TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE notes_table
    add column
        folder INTEGER REFERENCES folders_table(id)
        

